version: 2
updates:
  - package-ecosystem: pip
    directory: "/"
    schedule:
      interval: weekly
    versioning-strategy: increase-if-necessary
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: opencv-python-headless
        update-types: ["version-update:semver-major"]
      - dependency-name: pillow
        update-types: ["version-update:semver-major"]
    groups:
      python-runtime:
        patterns:
          - "*"
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: monthly
